services:
  mysql:
    image: mysql:9.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=banking
      - MYSQL_PASSWORD=banking
      - MYSQL_DATABASE=banking
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  postgres:
    image: postgres:18.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=banking
      - POSTGRES_USER=banking
      - POSTGRES_DB=banking
