replicaCount: 1

image:
  repository: spring-banking
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

spring:
  profile: postgres

database:
  enabled: true
  image:
    repository: postgres
    tag: "18.3"
  name: banking
  username: user
  password: pass
  service:
    port: 5432
  persistence:
    enabled: true
    storageClass: premium-rwo
    size: 10Gi

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
