# database init, supports mysql too
database=mysql
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost/banking}
spring.datasource.username=${MYSQL_USER:banking}
spring.datasource.password=${MYSQL_PASS:banking}
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always
