DROP TABLE transactions IF EXISTS;
DROP TABLE accounts IF EXISTS;
DROP TABLE account_types IF EXISTS;
DROP TABLE customers IF EXISTS;

CREATE TABLE customers (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR_IGNORECASE(30),
  email      VARCHAR(255),
  phone      VARCHAR(20),
  address    VARCHAR(255)
);
CREATE INDEX customers_last_name ON customers (last_name);

CREATE TABLE account_types (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
CREATE INDEX account_types_name ON account_types (name);

CREATE TABLE accounts (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_number VARCHAR(20),
  opened_date    DATE,
  balance        DECIMAL(19,2) DEFAULT 0.00,
  type_id        INTEGER NOT NULL,
  customer_id    INTEGER
);
ALTER TABLE accounts ADD CONSTRAINT fk_accounts_customers FOREIGN KEY (customer_id) REFERENCES customers (id);
ALTER TABLE accounts ADD CONSTRAINT fk_accounts_types FOREIGN KEY (type_id) REFERENCES account_types (id);
CREATE INDEX accounts_customer_id ON accounts (customer_id);

CREATE TABLE transactions (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id       INTEGER,
  transaction_date DATE,
  amount           DECIMAL(19,2),
  transaction_type VARCHAR(20),
  description      VARCHAR(255),
  balance_after    DECIMAL(19,2)
);
ALTER TABLE transactions ADD CONSTRAINT fk_transactions_accounts FOREIGN KEY (account_id) REFERENCES accounts (id);
CREATE INDEX transactions_account_id ON transactions (account_id);
