{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "banking.dbFullname" . }}
  labels:
    {{- include "banking.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    matchLabels:
      {{- include "banking.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "banking.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "banking.dbFullname" . }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "banking.dbFullname" . }}
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "banking.dbFullname" . }}
                  key: database
          ports:
            - containerPort: {{ .Values.database.service.port }}
              name: postgresql
          livenessProbe:
            tcpSocket:
              port: postgresql
          readinessProbe:
            tcpSocket:
              port: postgresql
          startupProbe:
            tcpSocket:
              port: postgresql
{{- end }}
