---
apiVersion: v1
kind: Service
metadata:
  name: banking
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: banking

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking
  labels:
    app: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking
  template:
    metadata:
      labels:
        app: banking
    spec:
      containers:
        - name: workload
          image: spring-banking:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: POSTGRES_URL
              value: "jdbc:postgresql://demo-db:5432/banking"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: username
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: demo-db
                  key: password
            - name: SERVICE_BINDING_ROOT
              value: /bindings
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /readyz
              port: http
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /livez
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          volumeMounts:
            - mountPath: /bindings/secret
              name: binding
              readOnly: true
      volumes:
        - name: binding
          projected:
            sources:
              - secret:
                  name: demo-db
