CREATE DATABASE IF NOT EXISTS banking;

ALTER DATABASE banking
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS 'banking'@'%' IDENTIFIED BY 'banking';

GRANT ALL PRIVILEGES ON banking.* TO 'banking'@'%';

FLUSH PRIVILEGES;
