CREATE TABLE IF NOT EXISTS account_types (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
);
CREATE INDEX ON account_types (name);

CREATE TABLE IF NOT EXISTS customers (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name  TEXT,
  email      TEXT,
  phone      TEXT,
  address    TEXT
);
CREATE INDEX ON customers (last_name);

CREATE TABLE IF NOT EXISTS accounts (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_number TEXT,
  opened_date    DATE,
  balance        DECIMAL(19,2) DEFAULT 0.00,
  type_id        INT NOT NULL REFERENCES account_types (id),
  customer_id    INT REFERENCES customers (id)
);
CREATE INDEX ON accounts (account_number);
CREATE INDEX ON accounts (customer_id);

CREATE TABLE IF NOT EXISTS transactions (
  id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id       INT REFERENCES accounts (id),
  transaction_date DATE,
  amount           DECIMAL(19,2),
  transaction_type TEXT,
  description      TEXT,
  balance_after    DECIMAL(19,2)
);
CREATE INDEX ON transactions (account_id);
